const CLOUD_NAME = import.meta.env.VITE_APP_CLOUD_NAME
const CLOUD_KEY_SECRET = import.meta.env.VITE_APP_KEY_SECRET
const CLOUD_KEY_PRESET = import.meta.env.VITE_APP_PRESET
const CLOUD_FOLDER_UPLOAD = import.meta.env.VITE_APP_TAG
export { CLOUD_KEY_PRESET, CLOUD_KEY_SECRET, CLOUD_NAME, CLOUD_FOLDER_UPLOAD }
